### ISSUE TITLE
Problemas com a funcionalidade "api.time(nome=' ')"

### ISSUE THREAD

**Issue by aeduaardo-dias** [vicenteneto/python-cartolafc#60]
Prezado,

Quando executo o exemplo básico  disponível na documentação tenho como retorno o seguinte erro...

>>> import cartolafc
>>> api = cartolafc.Api()
>>> time = api.time(nome='Yoguedes')
2019-10-25 08:34:15,713 - root - ERROR - Error parsing and checking json data: 
2019-10-25 08:34:15,721 - root - ERROR - No JSON object could be decoded

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    time = api.time(nome='Yoguedes')
  File "C:\Python27\lib\site-packages\cartolafc\api.py", line 277, in time
    data = self._request(url)
  File "C:\Python27\lib\site-packages\cartolafc\api.py", line 349, in _request
    raise error
CartolaFCOverloadError: Globo.com - Desculpe-nos, nossos servidores estÃ£o sobrecarregados.

**Comment by vicenteneto** [comment]
Devido à alguns problemas, a última versão da api `time` suporta apenas buscas por `id`.

Vou esperar a primeira rodada desse ano fechar, para ter os dados necessários para tentar readicionar o parametro por nome.
